name: Azure Sponsorship Costs Report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate_and_send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Build Docker Image
        run: docker build -t canalyzer:latest .

      - name: Echo Start
        run: |
         echo "Step 'Echo Start' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CANALYYZER_SMTP_HOST="${{ secrets.CANALYYZER_SMTP_HOST }}" \
            -e CANALYYZER_SMTP_PORT="${{ secrets.CANALYYZER_SMTP_PORT }}" \
            -e CANALYYZER_SMTP_USER="${{ secrets.CANALYYZER_SMTP_USER }}" \
            -e CANALYYZER_SMTP_PASSWORD="${{ secrets.CANALYYZER_SMTP_PASSWORD }}" \
            -e CANALYYZER_SMTP_FROM="${{ secrets.CANALYYZER_SMTP_FROM }}" \
            -e CANALYYZER_SMTP_TO="${{ secrets.CANALYYZER_SMTP_TO }}" \
            -e CANALYYZER_TENANT_ID="${{ secrets.CANALYYZER_TENANT_ID }}" \
            -e CANALYYZER_CLIENT_ID="${{ secrets.CANALYYZER_CLIENT_ID }}" \
            -e CANALYYZER_CLIENT_SECRET="${{ secrets.CANALYYZER_CLIENT_SECRET }}" \
            -e CANALYYZER_SUBSCRIPTION_ID="${{ secrets.CANALYYZER_SUBSCRIPTION_ID }}" \
            canalyzer:latest \
            /bin/bash -c "\
              echo \"Starting Docker container\""

      - name: Run canalyzer
        run: |
          echo "Step 'Run canalyzer' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              echo "Running canalyzer" && \
              canalyzer -o report -f markdown"

      - name: Convert markdown to HTML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              echo "Converting markdown to HTML" && \
              markdown_to_html report.md --css styles.css --with-summary --premailer -o html_report"

      - name: Convert HTML to PDF
        run: |
          echo "Step 'Convert markdown to HTML' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              echo "Converting HTML to PDF" && \
              cat html_report.html && \
              wkhtmltopdf html_report.html report.pdf"

      - name: SMTP
        run: |
          echo "Step 'SMTP' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              ls -la && \
              canalyzer_smtp html_report_summary.html report.pdf \
            "
