name: Azure Sponsorship Costs Report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate_and_send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Build Docker Image
        run: docker build -t canalyzer:latest .

      - name: Echo Start
        run: |
         echo "Step 'Echo Start' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CANALYYZER_SMTP_HOST="${{ secrets.CANALYYZER_SMTP_HOST }}" \
            -e CANALYYZER_SMTP_PORT="${{ secrets.CANALYYZER_SMTP_PORT }}" \
            -e CANALYYZER_SMTP_USER="${{ secrets.CANALYYZER_SMTP_USER }}" \
            -e CANALYYZER_SMTP_PASSWORD="${{ secrets.CANALYYZER_SMTP_PASSWORD }}" \
            -e CANALYYZER_SMTP_FROM="${{ secrets.CANALYYZER_SMTP_FROM }}" \
            -e CANALYYZER_SMTP_TO="${{ secrets.CANALYYZER_SMTP_TO }}" \
            -e CANALYYZER_TENANT_ID="${{ secrets.CANALYYZER_TENANT_ID }}" \
            -e CANALYYZER_CLIENT_ID="${{ secrets.CANALYYZER_CLIENT_ID }}" \
            -e CANALYYZER_CLIENT_SECRET="${{ secrets.CANALYYZER_CLIENT_SECRET }}" \
            -e CANALYYZER_SUBSCRIPTION_ID="${{ secrets.CANALYYZER_SUBSCRIPTION_ID }}" \
            canalyzer:latest \
            /bin/bash -c "\
            ls -la && \
              echo \"Starting Docker container\""

      - name: Run canalyzer
        run: |
          echo "Step 'Run canalyzer' executed"
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CANALYYZER_SMTP_HOST="${{ secrets.CANALYYZER_SMTP_HOST }}" \
            -e CANALYYZER_SMTP_PORT="${{ secrets.CANALYYZER_SMTP_PORT }}" \
            -e CANALYYZER_SMTP_USER="${{ secrets.CANALYYZER_SMTP_USER }}" \
            -e CANALYYZER_SMTP_PASSWORD="${{ secrets.CANALYYZER_SMTP_PASSWORD }}" \
            -e CANALYYZER_SMTP_FROM="${{ secrets.CANALYYZER_SMTP_FROM }}" \
            -e CANALYYZER_SMTP_TO="${{ secrets.CANALYYZER_SMTP_TO }}" \
            -e CANALYYZER_TENANT_ID="${{ secrets.CANALYYZER_TENANT_ID }}" \
            -e CANALYYZER_CLIENT_ID="${{ secrets.CANALYYZER_CLIENT_ID }}" \
            -e CANALYYZER_CLIENT_SECRET="${{ secrets.CANALYYZER_CLIENT_SECRET }}" \
            -e CANALYYZER_SUBSCRIPTION_ID="${{ secrets.CANALYYZER_SUBSCRIPTION_ID }}" \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              echo 'Running canalyzer' && \
              echo 'CANALYYZER_CLIENT_ID: ' \$CANALYYZER_CLIENT_ID && \
              echo 'CANALYYZER_TENANT_ID: ' \$CANALYYZER_TENANT_ID && \
              echo 'CANALYYZER_SUBSCRIPTION_ID: ' \$CANALYYZER_SUBSCRIPTION_ID && \
              canalyzer -o report -f markdown && \
              ls -la"

      - name: Convert markdown to HTML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            canalyzer:latest \
            /bin/bash -c "\
              set -e && \
              echo \"Converting markdown to HTML\" && \
              markdown_to_html report.md --css styles.css --with-summary --premailer -o html_report && \
              ls -la"
              
      - name: Convert HTML to Text
        run: |
         echo "Step 'Convert HTML to Text' executed"
         docker run --rm \
         -v ${{ github.workspace }}:/app \
         -w /app \
         canalyzer:latest \
         /bin/bash -c "\
         set -e && \
         ls -la && \
         echo 'Converting HTML to Text' && \
         html2text html_report.html > report.txt"
      
          
      - name: Send to Teams
        run: |
         echo "Step 'Send to Teams' executed"
         docker run --rm \
         -v ${{ github.workspace }}:/app \
         -w /app \
         canalyzer:latest \
         /bin/bash -c "\
         set -e && \
         ls -la && \
         echo 'Sending report to Teams' && \
         split -l 1000 report.txt report_part_ && \
         for f in report_part_*; do \
            report_content=\$(cat $f) && \
          if [[ -n \"\$report_content\" && \"\$report_content\" =~ [^[:space:]] ]]; then \
            json_payload=\$(jq -n --arg msg \"\$report_content\" '{
            \"@type\": \"MessageCard\",
            \"@context\": \"http://schema.org/extensions\",
            \"text\": \$msg
            }') && \
            curl -H \"Content-Type: application/json\" -d \"\$json_payload\" https://miraisecurity.webhook.office.com/webhookb2/b8dd144d-7268-42d2-a80c-2851a2b3648c@f8a0dab4-64f6-4c81-9db4-47a9f639039a/IncomingWebhook/b7723900de074e858e3388b206d452c3/783464b4-1cd9-4bff-b045-4303d051a7d8; \
          fi; \
          sleep 1; \
         done"
