name: Azure Sponsorship Costs Report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: canalyzer

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Cache Docker Image
        uses: actions/cache@v2
        with:
          path: /tmp/docker-images
          key: ${{ runner.os }}-docker-image-${{ env.IMAGE_NAME }}
        run: |
          mkdir -p /tmp/docker-images
          docker save ${{ env.IMAGE_NAME }}:latest -o /tmp/docker-images/${{ env.IMAGE_NAME }}.tar

  generate-report:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Load Cached Docker Image
        uses: actions/cache@v2
        with:
          path: /tmp/docker-images
          key: ${{ runner.os }}-docker-image-${{ env.IMAGE_NAME }}
        run: |
          docker load -i /tmp/docker-images/${{ env.IMAGE_NAME }}.tar

      - name: Run Canalyzer in Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CANALYZER_APPSETTINGS_PATH="${{ secrets.CANALYZER_APPSETTINGS_PATH }}" \
            ${{ env.IMAGE_NAME }}:latest \
            /bin/bash -c "\
            cat \$CANALYZER_APPSETTINGS_PATH > appsettings.json \
            && canalyzer -o report -f markdown \
            "

  # ... The rest of the jobs with the same changes for caching and loading the Docker image
