name: Azure Sponsorship Costs Report

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-and-send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t canalyzer:latest .

      - name: Run Steps in Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CANALYZER_APPSETTINGS_PATH="${{ secrets.CANALYZER_APPSETTINGS_PATH }}" \
            canalyzer:latest \
            /bin/bash -c "\
            cat \$CANALYZER_APPSETTINGS_PATH > appsettings.json \
            && canalyzer -o report -f markdown \
            && markdown_to_html report.md  --css styles.css --with-summary --premailer -o html_report \
            && wkhtmltopdf html_report.html report.pdf \
            && canalyzer_smtp html_report_summary.html report.md -a report.pdf \
